import { Router } from "express";
import OpenAI from "openai";
import { AnalyzeBinaryBody, AnalyzeForexBody } from "@workspace/api-zod";
import { logger } from "../lib/logger";

const router = Router();

const DISCLAIMER =
  "This analysis is generated by AI based only on the uploaded chart image. Financial markets are inherently uncertain, and no prediction is guaranteed. Always perform your own analysis and manage risk appropriately.";

function getOpenAI() {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error("OPENAI_API_KEY is not set");
  }
  return new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
}

function buildMoneyManagementSection(
  balance: number | null | undefined,
  currency: string | null | undefined,
  maxRiskPercent: number | null | undefined,
  experienceLevel: string | null | undefined,
): string {
  if (!balance) return "";
  return `
MONEY MANAGEMENT CONTEXT:
- Account Balance: ${balance} ${currency ?? "USD"}
- Max Risk Per Trade: ${maxRiskPercent ?? "not specified"}%
- Experience Level: ${experienceLevel ?? "not specified"}

You MUST include a full Money Management Report in the JSON under the "moneyManagement" key. 
Base all trade size recommendations on the account balance and confidence level of the analysis.
Rules:
- Never encourage increasing trade size after a loss
- Never imply losses can be recovered with certainty
- Never recommend unlimited Martingale
- Always prioritize capital preservation
- Martingale recommendation must be one of: NOT_RECOMMENDED, USE_WITH_CAUTION, OPTIONAL_HIGH_RISK, AVOID_COMPLETELY
`;
}

const BINARY_SYSTEM_PROMPT = `You are an expert binary options trading analyst with deep knowledge of technical analysis, price action, and risk management.

You analyze chart screenshots and provide professional, structured trading analysis reports.

IMPORTANT RULES:
- Never randomly guess. If the chart is blurry, cropped, lacks timeframe visibility, or has insufficient information, return direction: "NO_TRADE" and explain why.
- Always explain your reasoning. Never only say UP or DOWN without explanation.
- Be honest about uncertainty. Use NO_TRADE when signals are mixed or weak.
- Never claim guaranteed profits or certainty.

You MUST respond with a valid JSON object matching this exact structure (no markdown, no code blocks, raw JSON only):
{
  "direction": "UP" | "DOWN" | "NO_TRADE",
  "confidence": <number 0-100>,
  "riskLevel": "Very Low" | "Low" | "Medium" | "High" | "Extreme",
  "winProbability": <number 0-100>,
  "lossProbability": <number 0-100>,
  "estimatedAccuracy": <number 0-100>,
  "recommendedExpiry": "15 Seconds" | "30 Seconds" | "1 Minute" | "2 Minutes" | "3 Minutes" | "5 Minutes",
  "tradeQuality": "Excellent" | "Good" | "Average" | "Weak" | "Avoid",
  "marketStructureAnalysis": "<detailed analysis of trend, HH/LL, BOS, support/resistance, momentum, volatility, bias>",
  "candlestickAnalysis": "<analysis of visible candle formations>",
  "technicalLogic": "<full reasoning for UP/DOWN/NO_TRADE decision>",
  "tradingAdvice": "<why enter now, why wait, why avoid, where risk exists, how experienced traders would view this>",
  "summary": "<one paragraph summary>",
  "moneyManagement": null
}`;

const FOREX_SYSTEM_PROMPT = `You are an expert forex trading analyst with deep knowledge of technical analysis, smart money concepts, price action, and professional risk management.

You analyze forex chart screenshots and provide professional, structured trading analysis reports.

IMPORTANT RULES:
- Never randomly guess. If the chart is blurry, cropped, lacks timeframe visibility, or has insufficient information, return direction: "NO_TRADE" and explain why.
- Always explain your reasoning thoroughly.
- Be honest about uncertainty.
- Never claim guaranteed profits.

You MUST respond with a valid JSON object matching this exact structure (no markdown, no code blocks, raw JSON only):
{
  "direction": "BUY" | "SELL" | "NO_TRADE",
  "confidence": <number 0-100>,
  "riskLevel": "Very Low" | "Low" | "Medium" | "High" | "Extreme",
  "entryZone": "<price zone or description>",
  "stopLossZone": "<price zone or description>",
  "takeProfitZone": "<price zone or description>",
  "riskRewardRatio": "<e.g. 1:2.5>",
  "trendDirection": "<Bullish/Bearish/Ranging with detail>",
  "supportResistance": "<key levels identified>",
  "supplyDemandZones": "<supply and demand zone analysis>",
  "liquidityAnalysis": "<liquidity sweeps, BOS, CHoCH analysis>",
  "marketStructureAnalysis": "<full market structure breakdown>",
  "candlestickAnalysis": "<candlestick patterns visible>",
  "momentumAnalysis": "<momentum, RSI and MACD observations if visible>",
  "volatilityAnalysis": "<volatility assessment>",
  "technicalIndicators": "<EMA interaction, RSI, MACD observations if visible>",
  "summary": "<professional summary>",
  "moneyManagement": null
}`;

function buildMoneyManagementPrompt(
  balance: number | null | undefined,
  currency: string | null | undefined,
  maxRiskPercent: number | null | undefined,
  experienceLevel: string | null | undefined,
): string {
  if (!balance) return "";
  return `

Since account balance is provided, replace the "moneyManagement": null field with a full money management object:
{
  "suggestedTradeAmount": <number>,
  "maxSafeTradeAmount": <number>,
  "conservativeAmount": <number>,
  "aggressiveAmount": <number>,
  "amountReasoning": "<why these amounts>",
  "recommendedRiskPercent": <number>,
  "maxDailyRisk": <number based on balance>,
  "maxConsecutiveLosses": <number 2-5>,
  "dailyTradeLimit": <number 3-10>,
  "worthTaking": <true|false>,
  "martingaleRecommendation": "NOT_RECOMMENDED" | "USE_WITH_CAUTION" | "OPTIONAL_HIGH_RISK" | "AVOID_COMPLETELY",
  "martingaleExplanation": "<why this martingale recommendation>",
  "maxRecoverySteps": <number 0-3, NEVER unlimited>,
  "sessionAdvice": "<trade now, wait, reduce size, or skip>",
  "capitalProtectionNote": "<capital protection advice>",
  "finalTradingPlan": "<concise full trading plan summary>"
}

Account details: Balance=${balance} ${currency ?? "USD"}, MaxRisk=${maxRiskPercent ?? 2}%/trade, Experience=${experienceLevel ?? "Intermediate"}`;
}

router.post("/analyze/binary", async (req, res) => {
  const parseResult = AnalyzeBinaryBody.safeParse(req.body);
  if (!parseResult.success) {
    res.status(400).json({ error: "Invalid request body" });
    return;
  }

  const { imageBase64, platform, marketType, accountBalance, accountCurrency, maxRiskPercent, experienceLevel } =
    parseResult.data;

  try {
    const openai = getOpenAI();

    const userPrompt = `Analyze this binary options chart screenshot.

Platform: ${platform}
Market Type: ${marketType}
${buildMoneyManagementSection(accountBalance, accountCurrency, maxRiskPercent, experienceLevel)}

Provide a complete professional binary options analysis report as JSON.${buildMoneyManagementPrompt(accountBalance, accountCurrency, maxRiskPercent, experienceLevel)}`;

    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      max_tokens: 4096,
      messages: [
        {
          role: "system",
          content: BINARY_SYSTEM_PROMPT,
        },
        {
          role: "user",
          content: [
            {
              type: "text",
              text: userPrompt,
            },
            {
              type: "image_url",
              image_url: {
                url: `data:image/jpeg;base64,${imageBase64}`,
                detail: "high",
              },
            },
          ],
        },
      ],
    });

    const content = response.choices[0]?.message?.content;
    if (!content) {
      res.status(500).json({ error: "No response from AI" });
      return;
    }

    let parsed: Record<string, unknown>;
    try {
      // Strip any markdown code blocks if present
      const cleaned = content.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
      parsed = JSON.parse(cleaned);
    } catch {
      logger.error({ content }, "Failed to parse AI response as JSON");
      res.status(500).json({ error: "Failed to parse AI analysis response" });
      return;
    }

    res.json({ ...parsed, disclaimer: DISCLAIMER });
  } catch (err) {
    logger.error({ err }, "Binary analysis error");
    res.status(500).json({ error: "Analysis failed. Please try again." });
  }
});

router.post("/analyze/forex", async (req, res) => {
  const parseResult = AnalyzeForexBody.safeParse(req.body);
  if (!parseResult.success) {
    res.status(400).json({ error: "Invalid request body" });
    return;
  }

  const { imageBase64, platform, accountBalance, accountCurrency, maxRiskPercent, experienceLevel } =
    parseResult.data;

  try {
    const openai = getOpenAI();

    const userPrompt = `Analyze this forex chart screenshot.

Platform: ${platform}
${buildMoneyManagementSection(accountBalance, accountCurrency, maxRiskPercent, experienceLevel)}

Provide a complete professional forex trading analysis report as JSON.${buildMoneyManagementPrompt(accountBalance, accountCurrency, maxRiskPercent, experienceLevel)}`;

    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      max_tokens: 4096,
      messages: [
        {
          role: "system",
          content: FOREX_SYSTEM_PROMPT,
        },
        {
          role: "user",
          content: [
            {
              type: "text",
              text: userPrompt,
            },
            {
              type: "image_url",
              image_url: {
                url: `data:image/jpeg;base64,${imageBase64}`,
                detail: "high",
              },
            },
          ],
        },
      ],
    });

    const content = response.choices[0]?.message?.content;
    if (!content) {
      res.status(500).json({ error: "No response from AI" });
      return;
    }

    let parsed: Record<string, unknown>;
    try {
      const cleaned = content.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
      parsed = JSON.parse(cleaned);
    } catch {
      logger.error({ content }, "Failed to parse AI response as JSON");
      res.status(500).json({ error: "Failed to parse AI analysis response" });
      return;
    }

    res.json({ ...parsed, disclaimer: DISCLAIMER });
  } catch (err) {
    logger.error({ err }, "Forex analysis error");
    res.status(500).json({ error: "Analysis failed. Please try again." });
  }
});

export default router;
