import type { VercelRequest, VercelResponse } from "@vercel/node";
import OpenAI from "openai";

const DISCLAIMER =
  "This analysis is generated by AI based only on the uploaded chart image. Financial markets are inherently uncertain, and no prediction is guaranteed. Always perform your own analysis and manage risk appropriately.";

const BINARY_SYSTEM_PROMPT = `You are an expert binary options trading analyst with deep knowledge of technical analysis, price action, and risk management.

You analyze chart screenshots and provide professional, structured trading analysis reports.

IMPORTANT RULES:
- Never randomly guess. If the chart is blurry, cropped, lacks timeframe visibility, or has insufficient information, return direction: "NO_TRADE" and explain why.
- Always explain your reasoning. Never only say UP or DOWN without explanation.
- Be honest about uncertainty. Use NO_TRADE when signals are mixed or weak.
- Never claim guaranteed profits or certainty.

You MUST respond with a valid JSON object matching this exact structure (no markdown, no code blocks, raw JSON only):
{
  "direction": "UP" | "DOWN" | "NO_TRADE",
  "confidence": <number 0-100>,
  "riskLevel": "Very Low" | "Low" | "Medium" | "High" | "Extreme",
  "winProbability": <number 0-100>,
  "lossProbability": <number 0-100>,
  "estimatedAccuracy": <number 0-100>,
  "recommendedExpiry": "15 Seconds" | "30 Seconds" | "1 Minute" | "2 Minutes" | "3 Minutes" | "5 Minutes",
  "tradeQuality": "Excellent" | "Good" | "Average" | "Weak" | "Avoid",
  "marketStructureAnalysis": "<detailed analysis of trend, HH/LL, BOS, support/resistance, momentum, volatility, bias>",
  "candlestickAnalysis": "<analysis of visible candle formations>",
  "technicalLogic": "<full reasoning for UP/DOWN/NO_TRADE decision>",
  "tradingAdvice": "<why enter now, why wait, why avoid, where risk exists, how experienced traders would view this>",
  "summary": "<one paragraph summary>",
  "moneyManagement": null
}`;

function buildMoneyManagementPrompt(
  balance: number | null | undefined,
  currency: string | null | undefined,
  maxRiskPercent: number | null | undefined,
  experienceLevel: string | null | undefined,
): string {
  if (!balance) return "";
  return `

Since account balance is provided, replace "moneyManagement": null with:
{
  "suggestedTradeAmount": <number>,
  "maxSafeTradeAmount": <number>,
  "conservativeAmount": <number>,
  "aggressiveAmount": <number>,
  "amountReasoning": "<why these amounts>",
  "recommendedRiskPercent": <number>,
  "maxDailyRisk": <number based on balance>,
  "maxConsecutiveLosses": <number 2-5>,
  "dailyTradeLimit": <number 3-10>,
  "worthTaking": <true|false>,
  "martingaleRecommendation": "NOT_RECOMMENDED" | "USE_WITH_CAUTION" | "OPTIONAL_HIGH_RISK" | "AVOID_COMPLETELY",
  "martingaleExplanation": "<why this recommendation>",
  "maxRecoverySteps": <number 0-3, NEVER unlimited>,
  "sessionAdvice": "<trade now, wait, reduce size, or skip>",
  "capitalProtectionNote": "<capital protection advice>",
  "finalTradingPlan": "<concise full trading plan>"
}
Account: Balance=${balance} ${currency ?? "USD"}, MaxRisk=${maxRiskPercent ?? 2}%/trade, Experience=${experienceLevel ?? "Intermediate"}`;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const { imageBase64, platform, marketType, accountBalance, accountCurrency, maxRiskPercent, experienceLevel } =
    req.body ?? {};

  if (!imageBase64 || !platform || !marketType) {
    return res.status(400).json({ error: "imageBase64, platform, and marketType are required" });
  }

  if (!process.env.OPENAI_API_KEY) {
    return res.status(500).json({ error: "OPENAI_API_KEY is not configured" });
  }

  const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

  const userPrompt = `Analyze this binary options chart screenshot.
Platform: ${platform}
Market Type: ${marketType}
${accountBalance ? `Account Balance: ${accountBalance} ${accountCurrency ?? "USD"}, Max Risk: ${maxRiskPercent ?? 2}%/trade, Experience: ${experienceLevel ?? "Intermediate"}` : ""}
Provide a complete professional binary options analysis report as JSON.${buildMoneyManagementPrompt(accountBalance, accountCurrency, maxRiskPercent, experienceLevel)}`;

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      max_tokens: 4096,
      messages: [
        { role: "system", content: BINARY_SYSTEM_PROMPT },
        {
          role: "user",
          content: [
            { type: "text", text: userPrompt },
            {
              type: "image_url",
              image_url: {
                url: `data:image/jpeg;base64,${imageBase64}`,
                detail: "high",
              },
            },
          ],
        },
      ],
    });

    const content = response.choices[0]?.message?.content;
    if (!content) return res.status(500).json({ error: "No response from AI" });

    const cleaned = content.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
    const parsed = JSON.parse(cleaned);
    return res.json({ ...parsed, disclaimer: DISCLAIMER });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Analysis failed";
    return res.status(500).json({ error: message });
  }
}
