import type { VercelRequest, VercelResponse } from "@vercel/node";
import OpenAI from "openai";

const DISCLAIMER =
  "This analysis is generated by AI based only on the uploaded chart image. Financial markets are inherently uncertain, and no prediction is guaranteed. Always perform your own analysis and manage risk appropriately.";

const FOREX_SYSTEM_PROMPT = `You are an expert forex trading analyst with deep knowledge of technical analysis, smart money concepts, price action, and professional risk management.

You analyze forex chart screenshots and provide professional, structured trading analysis reports.

IMPORTANT RULES:
- Never randomly guess. If the chart is blurry, cropped, lacks timeframe visibility, or has insufficient information, return direction: "NO_TRADE" and explain why.
- Always explain your reasoning thoroughly.
- Be honest about uncertainty. Never claim guaranteed profits.

You MUST respond with a valid JSON object matching this exact structure (no markdown, no code blocks, raw JSON only):
{
  "direction": "BUY" | "SELL" | "NO_TRADE",
  "confidence": <number 0-100>,
  "riskLevel": "Very Low" | "Low" | "Medium" | "High" | "Extreme",
  "entryZone": "<price zone or description>",
  "stopLossZone": "<price zone or description>",
  "takeProfitZone": "<price zone or description>",
  "riskRewardRatio": "<e.g. 1:2.5>",
  "trendDirection": "<Bullish/Bearish/Ranging with detail>",
  "supportResistance": "<key levels identified>",
  "supplyDemandZones": "<supply and demand zone analysis>",
  "liquidityAnalysis": "<liquidity sweeps, BOS, CHoCH analysis>",
  "marketStructureAnalysis": "<full market structure breakdown>",
  "candlestickAnalysis": "<candlestick patterns visible>",
  "momentumAnalysis": "<momentum, RSI and MACD observations if visible>",
  "volatilityAnalysis": "<volatility assessment>",
  "technicalIndicators": "<EMA interaction, RSI, MACD observations if visible>",
  "summary": "<professional summary>",
  "moneyManagement": null
}`;

function buildMoneyManagementPrompt(
  balance: number | null | undefined,
  currency: string | null | undefined,
  maxRiskPercent: number | null | undefined,
  experienceLevel: string | null | undefined,
): string {
  if (!balance) return "";
  return `

Since account balance is provided, replace "moneyManagement": null with:
{
  "suggestedTradeAmount": <number>,
  "maxSafeTradeAmount": <number>,
  "conservativeAmount": <number>,
  "aggressiveAmount": <number>,
  "amountReasoning": "<why these amounts>",
  "recommendedRiskPercent": <number>,
  "maxDailyRisk": <number based on balance>,
  "maxConsecutiveLosses": <number 2-5>,
  "dailyTradeLimit": <number 3-10>,
  "worthTaking": <true|false>,
  "martingaleRecommendation": "NOT_RECOMMENDED" | "USE_WITH_CAUTION" | "OPTIONAL_HIGH_RISK" | "AVOID_COMPLETELY",
  "martingaleExplanation": "<why this recommendation>",
  "maxRecoverySteps": <number 0-3, NEVER unlimited>,
  "sessionAdvice": "<trade now, wait, reduce size, or skip>",
  "capitalProtectionNote": "<capital protection advice>",
  "finalTradingPlan": "<concise full trading plan>"
}
Account: Balance=${balance} ${currency ?? "USD"}, MaxRisk=${maxRiskPercent ?? 2}%/trade, Experience=${experienceLevel ?? "Intermediate"}`;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const { imageBase64, platform, accountBalance, accountCurrency, maxRiskPercent, experienceLevel } =
    req.body ?? {};

  if (!imageBase64 || !platform) {
    return res.status(400).json({ error: "imageBase64 and platform are required" });
  }

  if (!process.env.OPENAI_API_KEY) {
    return res.status(500).json({ error: "OPENAI_API_KEY is not configured" });
  }

  const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

  const userPrompt = `Analyze this forex chart screenshot.
Platform: ${platform}
${accountBalance ? `Account Balance: ${accountBalance} ${accountCurrency ?? "USD"}, Max Risk: ${maxRiskPercent ?? 2}%/trade, Experience: ${experienceLevel ?? "Intermediate"}` : ""}
Provide a complete professional forex analysis report as JSON.${buildMoneyManagementPrompt(accountBalance, accountCurrency, maxRiskPercent, experienceLevel)}`;

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      max_tokens: 4096,
      messages: [
        { role: "system", content: FOREX_SYSTEM_PROMPT },
        {
          role: "user",
          content: [
            { type: "text", text: userPrompt },
            {
              type: "image_url",
              image_url: {
                url: `data:image/jpeg;base64,${imageBase64}`,
                detail: "high",
              },
            },
          ],
        },
      ],
    });

    const content = response.choices[0]?.message?.content;
    if (!content) return res.status(500).json({ error: "No response from AI" });

    const cleaned = content.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
    const parsed = JSON.parse(cleaned);
    return res.json({ ...parsed, disclaimer: DISCLAIMER });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Analysis failed";
    return res.status(500).json({ error: message });
  }
}
